ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN echo "========> Dockerfile.rpi_bringup <========"

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
        ros-humble-isaac-ros-argus-camera \
        ros-humble-isaac-ros-apriltag

# setuptools-scm conflicts with setuptools, and is not needed
RUN pip3 uninstall -y \
    setuptools-scm
