image_width: 1280
image_height: 720
camera_name: rpi_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [786.0494 ,   0.     , 688.41104,
           0.     , 784.37525, 461.97678,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.315841, 0.089443, -0.000093, -0.000332, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [593.72913,   0.     , 709.64563,   0.     ,
           0.     , 708.18652, 477.11753,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
